modLoader = "javafml" #mandatory
loaderVersion = "[34,)" #mandatory
license = "MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "minecraftsuggestions" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Minecraft Suggestions" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://curseforge.com/minecraft/mc-mods/mc-suggestions"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java" #optional
authors = "Mawathilde"
description = '''

'''

[[dependencies.minecraftsuggestions]]
modId = "forge"
mandatory = true
versionRange = "[35.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.minecraftsuggestions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4]"
ordering = "NONE"
side = "BOTH"
[[dependencies.minecraftsuggestions]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.0,)"
ordering = "BEFORE"
side = "CLIENT"